# Generated by Django 3.2.6 on 2023-01-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
